import { Rubik } from 'next/font/google';

import './globals.css';

import Theme from './_providers/Theme';

const font = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Portal Demo',
    template: '%s | Portal Demo',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Theme>
        <body className={font.className}>{children}</body>
      </Theme>
    </html>
  );
}
